### ISSUE TITLE
Refuses to operate in a modern fully up to date browser

### ISSUE THREAD

**Issue by pugalo** [cokeeffekt/untap-wiki#2]
Sorry, this is a disgrace. You're not forcing me to fire up Chrome if I'm using last version of Firefox which is perfectly compatible with web standards.

Please build websites for the web, not just Google Chrome: https://thenextweb.com/dd/2017/11/28/please-build-websites-web-not-just-google-chrome/

Don't repeat the Internet Explorer 6 fiasco once again: https://www.theverge.com/2018/1/4/16805216/google-chrome-only-sites-internet-explorer-6-web-standards

**Comment by cokeeffekt** [comment]
Woah, hold up no body is forcing you to do anything. Im only one man and i develop in my free time on a site that is free to use, id rather push forward on new features as fast as i can with out having to worry about web standards (99% of my users don't care why should i). 

Firefox is missing a key piece of tech they have been promising for years and have never delivered. Webp support is the key reason why some browsers aren't supported, we aren't blocking browsers we are blocking features.

If i you don't like chrome try opera or vivaldi, they also hav webp support.

**Comment by starg09** [comment]
Just as to not make an entirely new issue, I wanted to point out that Edge 18+ (from the October 2018 Update) apparently supports webP images... So maybe that could be added to the supported browsers list?
